[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_build.f_cpu = 240000000L

; =========================================================
; PENGATURAN PROTOKOL UPLOAD (Ubah sesuai metode)
; Untuk kabel USB  : upload_protocol = esptool
; Untuk Nirkabel   : upload_protocol = espota
; =========================================================
upload_protocol = espota

; Aktifkan (hilangkan komentar) baris di bawah ini khusus untuk OTA
upload_port = 192.168.4.1
upload_flags =
    --port=3232
    --auth=
